package strings;

import java.util.ArrayList;

/**
 * Given a string, we have to find out all subsequences of it. A String is a
 * subsequence of a given String, that is generated by deleting some character
 * of a given string without changing its order.
 * 
 * Examples: Input : abc Output : a, b, c, ab, bc, ac, abc
 */
public class SubSequencesOfAString {
	private static ArrayList<String> arr = new ArrayList<>();

	public static void main(String[] args) {
		String str = "abc";
		printSubSequences(str, "");
		for (String subseq : arr)
			System.out.print(subseq + " ");
	}

	/**
	 * Pick And dont pick methodology -using recursion . We pick a character and add
	 * to add to the ans in one recursion call and in other we dont pick and
	 * continue recursion
	 * 
	 * @param str
	 * @param ans
	 */
	private static void printSubSequences(String str, String ans) {
		if (str.length() == 0) {
			arr.add(ans);
			return;
		}
		// add the first char and perform the operation
		printSubSequences(str.substring(1), ans + str.charAt(0));

		// without adding/picking the char
		printSubSequences(str.substring(1), ans);
	}

}
